UPDATE pais SET abr = 'AK' WHERE nom = 'Alaska';
UPDATE pais SET abr = 'NW' WHERE nom = 'North West Territory';
UPDATE pais SET abr = 'GL' WHERE nom = 'Greenland';
UPDATE pais SET abr = 'AL' WHERE nom = 'Alberta';
UPDATE pais SET abr = 'ON' WHERE nom = 'Ontario';
UPDATE pais SET abr = 'QC' WHERE nom = 'Quebec';
UPDATE pais SET abr = 'UW' WHERE nom = 'Western United States';
UPDATE pais SET abr = 'UE' WHERE nom = 'Eastern United States';
UPDATE pais SET abr = 'CA' WHERE nom = 'Central America';
UPDATE pais SET abr = 'VE' WHERE nom = 'Venezuela';
UPDATE pais SET abr = 'PE' WHERE nom = 'Peru';
UPDATE pais SET abr = 'BR' WHERE nom = 'Brazil';
UPDATE pais SET abr = 'AR' WHERE nom = 'Argentina';
UPDATE pais SET abr = 'IS' WHERE nom = 'Iceland';
UPDATE pais SET abr = 'GB' WHERE nom = 'Great Britain';
UPDATE pais SET abr = 'WE' WHERE nom = 'Western Europe';
UPDATE pais SET abr = 'NE' WHERE nom = 'Northern Europe';
UPDATE pais SET abr = 'SE' WHERE nom = 'Southern Europe';
UPDATE pais SET abr = 'SC' WHERE nom = 'Scandinavia';
UPDATE pais SET abr = 'UA' WHERE nom = 'Ukraine';
UPDATE pais SET abr = 'NF' WHERE nom = 'North Africa';
UPDATE pais SET abr = 'EG' WHERE nom = 'Egypt';
UPDATE pais SET abr = 'CG' WHERE nom = 'Congo';
UPDATE pais SET abr = 'EF' WHERE nom = 'East Africa';
UPDATE pais SET abr = 'SF' WHERE nom = 'South Africa';
UPDATE pais SET abr = 'MG' WHERE nom = 'Madagascar';
UPDATE pais SET abr = 'ME' WHERE nom = 'Middle East';
UPDATE pais SET abr = 'AG' WHERE nom = 'Afghanistan';
UPDATE pais SET abr = 'IN' WHERE nom = 'India';
UPDATE pais SET abr = 'UR' WHERE nom = 'Ural';
UPDATE pais SET abr = 'SN' WHERE nom = 'Sian';
UPDATE pais SET abr = 'CN' WHERE nom = 'China';
UPDATE pais SET abr = 'SB' WHERE nom = 'Siberia';
UPDATE pais SET abr = 'IK' WHERE nom = 'Irkutsk';
UPDATE pais SET abr = 'MN' WHERE nom = 'Mongolia';
UPDATE pais SET abr = 'YK' WHERE nom = 'Yakutsk';
UPDATE pais SET abr = 'KM' WHERE nom = 'Kamchatka';
UPDATE pais SET abr = 'JP' WHERE nom = 'Japan';
UPDATE pais SET abr = 'ID' WHERE nom = 'Indonesia';
UPDATE pais SET abr = 'NG' WHERE nom = 'New Guinea';
UPDATE pais SET abr = 'WA' WHERE nom = 'Western Australia';
UPDATE pais SET abr = 'EA' WHERE nom = 'Eastern Australia';
